### ISSUE TITLE
收藏界面出现问题

### ISSUE THREAD

**Issue by Mosslovist** [asmroneapp/Yuro#9]
打开收藏界面时，如图所示
Exception:解析数据失败：type'_Map<String 
dynamic>' is not a subtype of type
'List<dynamic>?' in type cast

![IMG_20241227_163537](https://github.com/user-attachments/assets/6772167a-4009-486f-9962-d29db5b12b0e)

**Comment by Mosslovist** [comment]
补充:<我喜欢的>出现问题，<我标记的>则正常显示

**Comment by Aioraio** [comment]
同上，会在主页遇到类似问题
![Screenshot_20241228_022234_one asmr yuro_edit_1695649609281232](https://github.com/user-attachments/assets/c54d1456-c1e7-4938-9e81-6e4e78f049ab)

**Comment by Mosslovist** [comment]
现在已经好了，感谢作者大大
